# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true
        uppercase_constants: true
        simplify_boolean_return: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        parameters_in_camelcaps: true
        phpunit_assertions: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        optional_parameters_at_the_end: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        avoid_perl_style_comments: true

filter:
    excluded_paths:
        - 'tests/*'

coding_style:
    php: {  }